name: CI/CD 

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0  # Use the version compatible with your setup

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/dev

      - name: Terraform Plan
        run: terraform plan -input=false
        working-directory: terraform/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: terraform/dev
